### ISSUE TITLE
跳过太快造成文本区不断上移

### ISSUE THREAD

**Issue by Syphurith** [xerysherry/uEmuera#10]
版本：0.2.6
症状：在大量文本刷过后，可能造成界面左下角上移，文本部分无法拖动；而且一旦开始上移，哪怕一行行按过去也会继续上移。不过此时依然可以一行行跳，也还可以用自动识别出来的按钮。最后啥历史文本都看不到。
引发：Megaten，YM，SQ等，有序列登录等功能的都可以造成，但实际上只要跳过文本速度太快也会造成。
建议：给个重置文本区和对应拖动响应的位置及相关控制数据的纠正按钮，在上移后按一下可以放到正确位置。

**Comment by xerysherry** [comment]
收到你的反馈啦，多谢
