### ISSUE TITLE
小反馈

### ISSUE THREAD

**Issue by 520MONV** [xerysherry/uEmuera#11]
很不容易……为了注册一个github的账号从凌晨1点整到了凌晨2点。而搞这个是为了像作者提问uemuera什么时候可以让era游戏mgt和AWT的图片显示得到完善修复，其中在0.28版中eraAWT一直卡在了加载页面无法加载，mgt则是图片加载错误无法显示。我用语言表达不是很清楚，只是想说uemuera对有图片的era加载不是很友好（小部分并不是全部），作为没有电脑只有手机的安卓党很支持作者开发，也希望可以为完善这个软件出一份微薄之力，希望这个启动器可以支持更多的era游戏，另外有一款模仿elona的era游戏——eraRL不知道是代码问题还是什么也无法在手机上运行…………希望可以得到解决

**Comment by xerysherry** [comment]
感谢你的反馈，因为工作一直比较忙，所以项目更新十分缓慢。
