### ISSUE TITLE
安卓10更新后无法找到游戏

### ISSUE THREAD

**Issue by shaoyangx** [xerysherry/uEmuera#12]
前几天平板更新安卓10以后发现游戏全部找不到了。没更新系统之前可以正常使用。更新系统后，打开软件游戏列表为空。
设备：华为M6
系统：安卓10

**Comment by xerysherry** [comment]
收到

**Comment by xerysherry** [comment]
可以把era游戏文件夹放入Android/data/xerysherry.uEmuera/files/下

**Comment by xerysherry** [comment]
已经修正
