### ISSUE TITLE
eraTW4.753的图片兼容问题

### ISSUE THREAD

**Issue by edliwracso** [xerysherry/uEmuera#15]
4.753版把图片格式改成了webp，与当前uEmuera似乎不兼容，会产生运行bug

**Comment by 0999312** [comment]
这里附上Emuera 1824 v9 WEBP的SRC（来自下载源）以方便更新修复：https://filebin.net/mnjo7efoujzt3ywc/src1824.7z?t=0njzo3f0
一周内有效，如果失效请及时通知或自行去eraロダ3号機那边下载。

**Comment by 0999312** [comment]
补档：https://filebin.net/mnjo7efoujzt3ywc

**Comment by edliwracso** [comment]
> 补档：https://filebin.net/mnjo7efoujzt3ywc

之前手动把webp改成了png所以没有继续关注，错过了你的链接，希望能补档。
另：请问 eraロダ3号機 是什么站点？谷歌查不到。

**Comment by 0999312** [comment]
补档：https://filebin.net/utebidhmumcbue2p
Filebin有强制七天的有效期...不过小文件无关紧要的时候会用得上。
eraロダ3号機这个去问问英文ERA WIKI或许会更好

**Comment by xerysherry** [comment]
webp支持最新版本已经支持。多谢使用
