### ISSUE TITLE
华为 安卓10.0加载不出游戏列表

### ISSUE THREAD

**Issue by Riona17** [xerysherry/uEmuera#16]
您好！首先感谢您开发这款软件，我也看了您对类似问题的回复并且多次尝试过，但是还是没有解决我的问题。在您建议的两个存储位置里都放了era游戏的文件夹，还是无法加载出游戏。
![Screenshot_20200723_224431_com huawei hidisk](https://user-images.githubusercontent.com/68699439/88300712-61be2200-cd36-11ea-86b1-1be00f347e94.jpg)
![Screenshot_20200723_224455_com huawei hidisk](https://user-images.githubusercontent.com/68699439/88300727-65ea3f80-cd36-11ea-9739-c132e92d26ba.jpg)

**Comment by xerysherry** [comment]
请尝试同最新版本看看
