### ISSUE TITLE
eraAS 立绘支持问题

### ISSUE THREAD

**Issue by x2119225** [xerysherry/uEmuera#17]
eraAS 在主页面立绘不显示（显示代码）以及AS调教页面的立绘和动画均不显示。
可以修复并支持AS图片和动画显示吗？万分感谢！每晚睡前在手机上玩会era已成生活习惯，离不开这个模拟器了，求更新啊~~~

**Comment by xerysherry** [comment]
使用最新版本0.2.9试试

**Comment by xerysherry** [comment]
另外请确认图片文件名非乱码
