### ISSUE TITLE
0.2.9版本出现文字错位bug

### ISSUE THREAD

**Issue by OmegawaveT** [xerysherry/uEmuera#19]
首先感谢大佬的开发。
机型 小米9se  Android10  miui12.0.3
在几种游戏界面中都有文字错位现象，目前测试了sqc，am，as。
![B937B2DAAA8B061493C848B95BEA9578](https://user-images.githubusercontent.com/58817972/102679518-60acf600-41eb-11eb-9054-dc72f9160232.jpg)
![64CCCEEED6B11D450DEACC8BBA28A4FA](https://user-images.githubusercontent.com/58817972/102679225-1296f300-41e9-11eb-916d-be66d375a972.jpg)
![82E456297F1CE072EE105DFB04E2BF0D](https://user-images.githubusercontent.com/58817972/102679227-13c82000-41e9-11eb-8c2c-d5c6f7896986.jpg)

**Comment by xerysherry** [comment]
好的，了解，后续将会处理
