### ISSUE TITLE
0.1.3 QA

### ISSUE THREAD

**Issue by xerysherry** [xerysherry/uEmuera#2]
0.1.3 问题和反馈

**Comment by syuraking** [comment]
eraAkumaMaid 里
SYSTEM_NEWGAME， line 16: ADDCHARA 99 
无法解释运行。

其它还有很多地方类似。

**Comment by xerysherry** [comment]
@syuraking 
1.确认安装版本是否为0.1.3。该游戏在0.1.2下无法执行。
2.确认CSV文件夹内*.csv文件已经转码为UTF8

**Comment by syuraking** [comment]
@xerysherry 好了，删除APP重装1.0.3后正常了……
之前升级安装的不正常，原因不明中
