### ISSUE TITLE
請問可以出 linux 版本嗎？

### ISSUE THREAD

**Issue by GHolk** [xerysherry/uEmuera#27]
emuera 需要 .NET 框架才能跑，但 linux 下用 wine 裝 .NET 很不方便， mono 又有 bug 。請問可以 build 一個 linux 版本或無需 .NET 的 windows 版嗎？

**Comment by xerysherry** [comment]
https://github.com/xerysherry/uEmuera/releases/tag/0.2.9c
这个链接了里提供了standalone版本，希望对你有帮助
