### ISSUE TITLE
TW4.840之后版本无法启动

### ISSUE THREAD

**Issue by WhitePr** [xerysherry/uEmuera#34]
TW4.840之后无法启动 会卡在如下页面![Screenshot_20220520-152052_uEmuera.png](https://user-images.githubusercontent.com/76523578/169465806-5047009c-b5d8-4f2c-b1ec-24005e4f097b.png)
但是TW4.830版本没有这个问题
Android版本:12

**Comment by WhitePr** [comment]
[TW4.8.0 (已经转码)](https://drive.google.com/file/d/1JmsqmF6If6Sf7lCkeOmb81DQUeF4Tcxl/view?usp=drivesdk)

**Comment by imhubai** [comment]
你的显示图片正常嘛 我的全白 包括title

**Comment by WhitePr** [comment]
> 你的显示图片正常嘛 我的全白 包括title

4.830运行完全正常 图片正常显示 包括动画地图
![Screenshot_20220522-000412_uEmuera.png](https://user-images.githubusercontent.com/76523578/169657430-b1810799-c388-43b0-bb3a-5d5ec9157bab.png)

**Comment by imhubai** [comment]
看起来是我用的口上汉化版问题？你的是原版诶
我现在用的是雨水汉化版

**Comment by imhubai** [comment]
还是谢谢啦 可以试试4.842版本，我的可以加载进去,如果开了显示警告会有一大片webp的报错(rename....)

**Comment by WhitePr** [comment]
> 还是谢谢啦 可以试试4.842版本，我的可以加载进去,如果开了显示警告会有一大片webp的报错(rename....)

我这边4.842原版一样打不开 841也不行 都是转过码的

**Comment by xerysherry** [comment]
已经更新版本
