### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by Tsuki321** [xerysherry/uEmuera#37]
Seems like the app is not Using the translations fully resulting in a partially translated text, mostly affected are the Names, Abilities, Talents, Experience, especially on the cheats section and other ERA games.
![Screenshot_2022-11-12-10-59-01-94](https://user-images.githubusercontent.com/103306466/201453495-60b967d4-7b81-4f5e-9fb7-67d048ae3a0b.jpg)
![Screenshot_2022-11-12-10-58-41-77](https://user-images.githubusercontent.com/103306466/201453498-68ae04e5-9358-4fd7-9daa-7e28d05a67bb.jpg)

**Comment by sanscriptum** [comment]
This is out of scope for this project as the translation part comes from Emuera Anchor functionality itself.

**Comment by Tsuki321** [comment]
The anchor is the issue? Anyways thx for that
