### ISSUE TITLE
QA

### ISSUE THREAD

**Issue by xerysherry** [xerysherry/uEmuera#4]

**Comment by Syphurith** [comment]
有关如何自动判决文本编码的提示
* 各个文本编码都有可见字符区
* 语言有对应的常见字符
* C#可以用来转换编码

所以
* 读取完整文本成Byte[]
* 用Encoding的GetEncoding获得常用编码，如936/932，以及备用的Encoding.UTF8
* 对读出的二进制进行GetString，然后用Regexp替换掉可见字符为空
* 统计字串长度，因为换掉了所有的可见字符，对正常的文本，基本就没几个字符了
* 也可以通过常见字符进行识别，如探测中文标点，探测日文假名数量等

推荐试试上面的办法，可以探测有限编码集(UTF/GBK/SHIFTJIS)中的字符编码，免除手动批量转换，运转更容易。理论上也可以出一个专用软件。*祝各位良绅玩得开心。*

**Comment by xerysherry** [comment]
你的建议非常好，UNITY的Android版本只支持了Encoding.UTF8编码。

**Comment by Syphurith** [comment]
理论上存在UTF8和GBK/ShiftJIS的编码转换序列，不过真这样怕是不如带入Iconv比较省事。*刚才查了下Unity3D这方面的支持还真是阉割过的，确实麻烦*
