### ISSUE TITLE
魔王的脚本解析出错

### ISSUE THREAD

**Issue by pokemonchw** [xerysherry/uEmuera#7]
───────────────────────────────────────────────────────────────
　▌Commands
　[100] 调教                　[101] 能力显示            　[102] 地下城              
　[103] 处刑                　[104] 迎击                　[105] 能力值提升          
　[---] 　　　　            　[107] 购物                　[108] 换装                
　[109] 侵略                　[---] 　　　　　          　[---] 　　　　　          
　[120] 召唤                　[199] 休息                　[200] 保存                
　[300] 读取                　[777] 设定                　[888] 通信                
═══════════════════════════════════════════════════════════════
100
===============================================================================================================================
请选择调教的奴隶
-------------------------------------------------------------------------------------------------------------------------------
[ 1] 玛奥                LV   1　HP[********] 调教回数:0  
SHOP_FUNCTION.ERBの21行目でエラーが発生しました:
		IF TALENT:COUNT:爱慕
エラー内容："爱慕"は解釈できない識別子です
現在の関数：@SHOW_LIST_TRAINABLE（SHOP_FUNCTION.ERBの7行目）
関数呼び出しスタック：
↑SHOP.ERBの231行目（関数@SELECT_TARGET内）
↑SHOP.ERBの66行目（関数@USERSHOP内）
※※※ログファイルをgame/eramaouEX 0.90/emuera.logに出力しました※※※

**Comment by xerysherry** [comment]
该错误为“爱慕”无法识别了。这个问题一般是汉化CSV与ERB中不统一，或者未汉化完全导致。检查CSV/Talent.csv中爱慕文本翻译

**Comment by pokemonchw** [comment]
@xerysherry 但是在windows上跑正常……

**Comment by xerysherry** [comment]
*.csv文件是否装换为UTF8编码了？

**Comment by pokemonchw** [comment]
编码都统一校验过，没有问题

**Comment by xerysherry** [comment]
能否给一下游戏包

**Comment by pokemonchw** [comment]
就储备库里的
http://xiaxiansy.pw/sy/index.php/EraTheWorld
http://xiaxiansy.pw/sy/index.php/Era%E9%AD%94%E7%8E%8B

**Comment by xerysherry** [comment]
我测试了《【汉化？】era毛奥ex920更新》没有问题

**Comment by pokemonchw** [comment]
[截图](http://pan.diemoe.net/s/LnxhN1)
在游戏载入自检中都是这样的错误
我检查了一下，初步推测应该是linux系统下，mono环境，uEmuera解析脚本的时候，对非英文的对象创建无效之类的问题

**Comment by xerysherry** [comment]
从截图上看，文件以及读取出来了。但是chara*.csv文件中的定义与abl.csv, exp.csv等csv文件定义不匹配。
请检查一下，比如你截图中的《百合属性》，该文本在Chara/Chara*.csv出现，但是在abl.csv中未被定义，注意简繁差异

**Comment by pokemonchw** [comment]
然而游戏包是从储备库直接下载的，并能够在wine里正常运行(除了少部分mono和.net的函数差异需要自己手动调整代码)

**Comment by xerysherry** [comment]
能否把你测试用的游戏包发给我看看

**Comment by pokemonchw** [comment]
[原链接](https://tieba.baidu.com/p/5700033459?pid=120743381602&red_tag=0573479505#120743381602)

**Comment by xerysherry** [comment]
我没找到下载的地址，希望直接给下载链接
